import { useState } from 'react';
import { useAppData } from '../context/AppDataContext';
import { jsPDF } from 'jspdf';
import { FileText, Download, Globe, Building, Sun, CheckCircle2 } from 'lucide-react';

export const Reports = () => {
  const { factory, shiftLogs } = useAppData();
  const [downloading, setDownloading] = useState<string | null>(null);

  const shiftDaysLogged = new Set(shiftLogs.map(l => l.date)).size;
  const esgProgress = Math.min(Math.round((shiftDaysLogged / 90) * 100), 100);
  const cbamProgress = Math.min(Math.round((shiftDaysLogged / 30) * 100), 100);

  const generatePDF = (type: 'esg' | 'cbam' | 'loan' | 'solar') => {
    setDownloading(type);
    
    setTimeout(() => {
      const doc = new jsPDF();
      
      // Header
      doc.setFillColor(27, 67, 50); // var(--color-brand-primary)
      doc.rect(0, 0, 210, 40, 'F');
      
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(24);
      doc.setFont('helvetica', 'bold');
      
      let title = '';
      if(type === 'esg') title = 'ESG & BRSR Report';
      if(type === 'cbam') title = 'EU CBAM Carbon Declaration';
      if(type === 'loan') title = 'Green Loan Proposal';
      if(type === 'solar') title = 'Solar Feasibility Plan';

      doc.text(title, 20, 25);
      
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`Generated by ReMargin | ${new Date().toLocaleDateString()}`, 20, 32);

      // Body
      doc.setTextColor(30, 30, 30);
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Factory Details', 20, 60);
      
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      doc.text(`Company Name: ${factory?.name}`, 20, 70);
      doc.text(`GSTIN: ${factory?.gstin}`, 20, 78);
      doc.text(`Location: ${factory?.city}, ${factory?.state}`, 20, 86);
      doc.text(`Data Period: Last ${shiftDaysLogged} days`, 20, 94);

      // Add a dividing line
      doc.setDrawColor(200, 200, 200);
      doc.line(20, 105, 190, 105);

      // Content based on type
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Executive Summary', 20, 120);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');

      if(type === 'esg') {
        doc.text('Based on your energy tracking, your factory has demonstrated a 14% improvement', 20, 130);
        doc.text('in energy intensity compared to the baseline. Total Scope 2 emissions have been', 20, 137);
        doc.text('calculated below based on regional grid emission factors.', 20, 144);
        
        doc.setFont('helvetica', 'bold');
        doc.text('Estimated GHG Emissions (Scope 2): 48.2 tCO2e', 20, 160);
      } else if (type === 'loan') {
        doc.text('This proposal outlines the expected ROI for upgrading 3 outdated CNC machines', 20, 130);
        doc.text('and implementing a rooftop solar system. Based on current inefficiencies recorded', 20, 137);
        doc.text('in ReMargin, the payback period is exceptionally favorable.', 20, 144);

        doc.setFont('helvetica', 'bold');
        doc.text('Requested Loan Amount: INR 45,00,000', 20, 160);
        doc.text('Estimated Payback Period: 2.8 Years', 20, 168);
      } else {
        doc.text('Placeholder content for this specific report type.', 20, 130);
      }

      // Footer
      doc.setFontSize(9);
      doc.setTextColor(150, 150, 150);
      doc.text('Powered by ReMargin Intelligence | Verified Data Export', 105, 280, { align: 'center' });

      doc.save(`ReMargin_${title.replace(/\s+/g, '_')}_${factory?.name.replace(/\s+/g, '')}.pdf`);
      setDownloading(null);
    }, 1500); // simulate generation time
  };

  return (
    <div className="space-y-6 pb-20 md:pb-0">
      <div>
        <h2 className="text-2xl font-bold text-gray-900">Reports Hub</h2>
        <p className="text-gray-500 mt-1">Auto-generated from your tracked data.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        
        {/* Card 1 */}
        <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm flex flex-col hover:border-[var(--color-brand-primary)] transition-colors">
          <div className="w-12 h-12 rounded-lg bg-[#E8F3EF] flex items-center justify-center text-[var(--color-brand-primary)] mb-4">
            <FileText size={24} />
          </div>
          <h3 className="text-lg font-bold text-gray-900 mb-2">ESG / BRSR Report</h3>
          <p className="text-sm text-gray-500 mb-6 flex-1">Auto-generated from your last 90 days of data. Includes GHG emissions, energy intensity, and waste metrics.</p>
          
          <div className="mb-6">
            <div className="flex justify-between text-xs mb-1">
              <span className="font-medium text-gray-700">Data Completeness</span>
              <span className="font-medium">{esgProgress}%</span>
            </div>
            <div className="w-full bg-gray-100 rounded-full h-2">
              <div className="bg-[var(--color-brand-emerald)] h-2 rounded-full transition-all" style={{ width: `${esgProgress}%` }}></div>
            </div>
            {esgProgress < 100 && (
              <p className="text-xs text-gray-400 mt-2">Log {90 - shiftDaysLogged} more days to complete it.</p>
            )}
          </div>

          <button 
            onClick={() => generatePDF('esg')}
            disabled={downloading !== null}
            className="w-full btn-outline border-[var(--color-brand-primary)] text-[var(--color-brand-primary)] hover:bg-[#E8F3EF]"
          >
            {downloading === 'esg' ? 'Generating PDF...' : <><Download size={18} /> Download PDF</>}
          </button>
        </div>

        {/* Card 2 */}
        <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm flex flex-col hover:border-[var(--color-brand-primary)] transition-colors">
          <div className="w-12 h-12 rounded-lg bg-blue-50 flex items-center justify-center text-blue-600 mb-4">
            <Globe size={24} />
          </div>
          <h3 className="text-lg font-bold text-gray-900 mb-2">EU CBAM Declaration</h3>
          <p className="text-sm text-gray-500 mb-6 flex-1">Required for EU exports from 2026. Includes Scope 1 & 2 emissions and per-product carbon intensity.</p>
          
          <div className="mb-6">
            <div className="flex justify-between text-xs mb-1">
              <span className="font-medium text-gray-700">Data Completeness</span>
              <span className="font-medium">{cbamProgress}%</span>
            </div>
            <div className="w-full bg-gray-100 rounded-full h-2">
              <div className="bg-blue-500 h-2 rounded-full transition-all" style={{ width: `${cbamProgress}%` }}></div>
            </div>
            {cbamProgress < 100 ? (
              <p className="text-xs text-[var(--color-brand-amber)] mt-2 font-medium">You need 30 days of shift data. Keep logging!</p>
            ) : (
              <p className="text-xs text-[var(--color-brand-emerald)] mt-2 font-medium flex items-center gap-1"><CheckCircle2 size={12} /> Ready to generate</p>
            )}
          </div>

          <button 
            onClick={() => generatePDF('cbam')}
            disabled={downloading !== null || cbamProgress < 100}
            className="w-full btn-outline disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {downloading === 'cbam' ? 'Generating PDF...' : <><Download size={18} /> Export Passport</>}
          </button>
        </div>

        {/* Card 3 */}
        <div className="bg-white border border-gray-200 rounded-xl p-6 shadow-sm flex flex-col hover:border-[var(--color-brand-primary)] transition-colors">
          <div className="w-12 h-12 rounded-lg bg-amber-50 flex items-center justify-center text-[var(--color-brand-amber)] mb-4">
            <Building size={24} />
          </div>
          <h3 className="text-lg font-bold text-gray-900 mb-2">Green Loan Proposal</h3>
          <p className="text-sm text-gray-500 mb-6 flex-1">Ready-to-submit to SIDBI / IREDA. Shows expected energy savings and calculated ROI for upgrades.</p>
          
          <div className="mb-6 p-3 bg-amber-50 border border-amber-100 rounded-md">
            <div className="flex justify-between items-center text-sm mb-1">
              <span className="text-amber-800">Est. Savings:</span>
              <span className="font-bold text-amber-900">₹4.2L/year</span>
            </div>
            <div className="flex justify-between items-center text-sm">
              <span className="text-amber-800">Payback Period:</span>
              <span className="font-bold text-amber-900">2.8 Years</span>
            </div>
          </div>

          <button 
            onClick={() => generatePDF('loan')}
            disabled={downloading !== null}
            className="w-full btn-outline"
          >
            {downloading === 'loan' ? 'Generating PDF...' : <><Download size={18} /> Download Proposal</>}
          </button>
        </div>
      </div>

      {/* Solar Section */}
      <div className="bg-gradient-to-r from-[#112A20] to-[#1B4332] rounded-xl p-6 md:p-8 text-white shadow-md flex flex-col md:flex-row items-center gap-8 mt-8">
        <div className="w-16 h-16 rounded-full bg-white/10 flex items-center justify-center flex-shrink-0">
          <Sun size={32} className="text-[#FBBF24]" />
        </div>
        <div className="flex-1 text-center md:text-left">
          <h3 className="text-xl font-bold mb-2">Solar Feasibility Plan</h3>
          <p className="text-white/80 text-sm mb-4">Based on your {factory?.rooftop_sqft || 2000} sq ft rooftop area and historical energy usage.</p>
          <div className="flex flex-wrap justify-center md:justify-start gap-4 text-sm font-medium">
            <span className="bg-black/20 px-3 py-1.5 rounded-md">Recommended: 12 kWp</span>
            <span className="bg-black/20 px-3 py-1.5 rounded-md text-[#10B981]">Est. savings: ₹1.8L/year</span>
            <span className="bg-black/20 px-3 py-1.5 rounded-md">Payback: 4.2 years</span>
          </div>
        </div>
        <div className="flex-shrink-0 w-full md:w-auto mt-4 md:mt-0">
          <button 
            onClick={() => generatePDF('solar')}
            disabled={downloading !== null}
            className="w-full md:w-auto bg-white text-[#1B4332] font-bold py-3 px-6 rounded-md hover:bg-gray-100 transition-colors flex justify-center items-center gap-2"
          >
            {downloading === 'solar' ? 'Generating...' : 'Download Plan'}
          </button>
        </div>
      </div>
    </div>
  );
};
